### ISSUE TITLE
Simswap dont works

### ISSUE THREAD

**Issue by nascacorp** [woctezuma/SimSwap-colab#7]
Hi dude, i get this error when i try to use simswap
AttributeError: 'dict' object has no attribute 'to'

thanks for all your work!

**Comment by woctezuma** [comment]
Right.

```
Traceback (most recent call last):
  File "/content/SimSwap/test_wholeimage_swapsingle.py", line 51, in <module>
    model = create_model(opt)
  File "/content/SimSwap/models/models.py", line 18, in create_model
    model.initialize(opt)
  File "/content/SimSwap/models/fs_model.py", line 69, in initialize
    self.netArc = self.netArc.to(device)
AttributeError: 'dict' object has no attribute 'to'
```

Related:
- https://github.com/neuralchen/SimSwap/issues/399

**Comment by woctezuma** [comment]
Fixed. Thank you for raising the issue!
